import { ThemeProvider } from "@/components/theme-provider"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import Crisp from './crisp'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import './globals.css'
import PlausibleProvider from 'next-plausible'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PlausibleProvider domain="https://j8s84oo.64.23.249.87.sslip.io/">
            <Crisp />
            <SpeedInsights />
            <Analytics />
            {children}
          </PlausibleProvider>
        </ThemeProvider>
      </body>
    </html >
  )
}
