import { ThemeProvider } from "@/components/theme-provider"
import Crisp from './crisp'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import './globals.css'
import PlausibleProvider from 'next-plausible'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <PlausibleProvider
        domain="j8s84oo.64.23.249.87.sslip.io"
        customDomain="https://plausible-f48o844.64.23.249.87.sslip.io"
        trackFileDownloads={true}
        trackOutboundLinks={true}
        selfHosted={true}
        enabled={true}>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Crisp />
            {children}
          </ThemeProvider>
        </body>
      </PlausibleProvider>
    </html >
  )
}
